Repository CSID-DGU/2023-02-CECD2-6, pull requests merged in 2023-09, with the labels that each got.

#3 [Extra] .github의 md파일 인코딩 문제
  .github/ISSUE_TEMPLATE/README.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/experiment.md
  .github/ISSUE_TEMPLATE/extra.md
  .github/ISSUE_TEMPLATE/feature-development.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/commit_template_manual.md
  .github/pull_request_template.md
  .gitignore
Labels: documentation

#5 [Feat] Add optional features for RSS/newsGenerator
  .gitignore
  RSS/RssParser/base.py
  RSS/RssParser/chosun.py
  RSS/main.py
  RSS/newsGenerator.py
  RSS/output.json
Labels: feature

#6 [Feat] RSS와 TextRank 통합 및 데이터베이스 연결
  .DS_Store
  .gitignore
  NewsData/RSS/RSS.py
  NewsData/RSS/RssParser/base.py
  NewsData/RSS/RssParser/chosun.py
  NewsData/RSS/newsGenerator.py
  NewsData/RSS/rssConfig.json
  NewsData/RSS/utils.py
  NewsData/newsdata.py
  NewsData/output.json
  NewsData/textrank/TextRank.py
  NewsData/textrank/__pycache__/TextRank.cpython-310.pyc
  NewsData/textrank/textrank/__init__.py
  NewsData/textrank/textrank/__pycache__/__init__.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/rank.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/sentence.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/summarizer.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/utils.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/word.cpython-310.pyc
  NewsData/textrank/textrank/rank.py
  NewsData/textrank/textrank/sentence.py
  NewsData/textrank/textrank/summarizer.py
  NewsData/textrank/textrank/utils.py
  NewsData/textrank/textrank/word.py
Labels: feature

#7 [Feat] RSS를 통한 뉴스 데이터 수집 & TextRank를 통한 키워드 추출
  .DS_Store
  .github/ISSUE_TEMPLATE/README.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/experiment.md
  .github/ISSUE_TEMPLATE/extra.md
  .github/ISSUE_TEMPLATE/feature-development.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/commit_template_manual.md
  .github/pull_request_template.md
  .gitignore
  NewsData/RSS/RSS.py
  NewsData/RSS/RssParser/base.py
  NewsData/RSS/RssParser/chosun.py
  NewsData/RSS/newsGenerator.py
  NewsData/RSS/rssConfig.json
  NewsData/RSS/utils.py
  NewsData/newsdata.py
  NewsData/output.json
  NewsData/textrank/TextRank.py
  NewsData/textrank/__pycache__/TextRank.cpython-310.pyc
  NewsData/textrank/textrank/__init__.py
  NewsData/textrank/textrank/__pycache__/__init__.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/rank.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/sentence.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/summarizer.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/utils.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/word.cpython-310.pyc
  NewsData/textrank/textrank/rank.py
  NewsData/textrank/textrank/sentence.py
  NewsData/textrank/textrank/summarizer.py
  NewsData/textrank/textrank/utils.py
  NewsData/textrank/textrank/word.py
Labels: documentation, feature

#9 [Docs] Update .gitignore
  .gitignore
  NewsData/RSSOutputExample.json
  NewsData/output.json
  NewsData/textrank/__pycache__/TextRank.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/__init__.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/rank.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/sentence.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/summarizer.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/utils.cpython-310.pyc
  NewsData/textrank/textrank/__pycache__/word.cpython-310.pyc
Labels: documentation
